DCE-13 Job Subscription Create (Backend)
DeSimone-Seattle-University-2023-Team2/desimone pull request #11
Opened 2024-01-12 02:31 UTC by mahir-cognitiv

2024-01-12 23:46 UTC, giaou approved these changes

2024-01-13 00:39 UTC, ducmvo commented on src/Infrastructure/Repositories/JobSubscriptionRepository.cs
>      public Task<List<JobSubscription>> GetJobSubscriptionsByJobId(int jobId)
can we have unit tests for `GetJobSubscriptionsByJobId`, `GetJobSubscriptionByJobSubscriptionId`, and `DeleteJobSubscription`?

2024-01-13 00:41 UTC, ducmvo requested changes
some comment of unit tests and comments. Otherwise, looking great!

2024-01-13 23:57 UTC, mahir-cognitiv commented on src/Infrastructure/Repositories/JobSubscriptionRepository.cs
>      public Task<List<JobSubscription>> GetJobSubscriptionsByJobId(int jobId)
we dont have this method in the service GetJobSubscriptionByJobSubscriptionId, nor can I think of a use case for it. We will always be getting all of the subscriptions by JobId, or all at once. I will write tests for the others

2024-01-14 02:39 UTC, ducmvo approved these changes

2024-01-14 03:32 UTC, merged