Feature/dce 15 add back button to job details
DeSimone-Seattle-University-2023-Team2/desimone pull request #13
Opened 2024-01-12 23:12 UTC by mahir-cognitiv

2024-01-12 23:54 UTC, giaou approved these changes

2024-01-13 03:58 UTC, ducmvo requested changes
some feedback and suggestion on routings

2024-01-13 03:58 UTC, ducmvo commented on src/Presentation/Components/UI/MonitoringTable.razor
> +            <td class="nav-link" @onclick="() => GoToJobDetails(currentJob.Id.Value)">@job.Id</td>
Please use supported NavLink component for routing
ref: [NavLink Class](https://learn.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.components.routing.navlink?view=aspnetcore-8.0&viewFallbackFrom=net-8.0)

```suggestion
            <td><NavLink class="nav-link" href=@($"/monitoring/{job.Id}")>@job.Id</NavLink></td>
```

2024-01-13 03:58 UTC, ducmvo commented on src/Presentation/Components/UI/MonitoringTable.razor
> +    }
this can be removed with use of NavLink

2024-01-13 03:58 UTC, ducmvo commented on src/Presentation/Components/Pages/JobDetails.razor
> +    Job job;
```suggestion
    private Job? _job;
```

2024-01-13 03:58 UTC, ducmvo commented on src/Presentation/Components/Pages/JobDetails.razor
> +    }
parameter JobId is automatically set using dynamic route {jobId:int}, so spliting Uri is unnecessary

```suggestion
    private Job? _job;
    protected override void OnInitialized() => _job = JobService.GetJobById(JobId).Result;
```

2024-01-14 01:55 UTC, mahir-cognitiv commented on src/Presentation/Components/Pages/JobDetails.razor
> +    }
we already throw a keynotfound exception in the jobRepository if the job returned is null. The UI for showing the job not found is a different 404 page that needs to be designed (out of scope for this task), which i have added to the backlog

2024-01-14 02:40 UTC, ducmvo approved these changes

2024-01-14 03:33 UTC, merged