Created the homepage with navigation to the 3 main pages
DeSimone-Seattle-University-2023-Team2/desimone pull request #21
Opened 2024-01-19 02:19 UTC by theslic

Created the home page with navigation to the main 3 pages: dashboard, monitoring, and submission each with a short description of the page. The page should direct the user to the login page when selecting one of 3 options.

2024-01-19 05:46 UTC, ducmvo requested changes
We can replace custom css and use bootstrap instead.
For example:
```html
<div class="container d-flex flex-column justify-content-center align-items-center">
    <div class="d-flex justify-content-center mt-xl-5"><h1>Cloud Compute Job Management System</h1></div><br />
    <div class="d-flex justify-content-center"><h3>Simplifying job submission with real-time</h3></div>
    <div class="d-flex justify-content-center mb-xl-5"><h3>progression tracking and cost management</h3></div><br />

    <div class="container d-flex flex-row gap-lg-5 mt-xl-5">
        <div class="card">
            <NavLink class="btn btn-outline-dark py-xl-5 px-5 h-100" href="dashboard">
                <h3 class="mb-5">Dashboard</h3>
                <p>The dashboard provides a concise summary of key metrics for convenient viewing.</p>
            </NavLink>
        </div>
        <div class="card">
            <NavLink class="btn btn-outline-dark py-xl-5 px-5 h-100" href="submission">
                <h3 class="mb-5">Submission</h3>
                <p>The submission page is where users input various job details for calculation.</p>
            </NavLink>
        </div>
        <div class="card">
            <NavLink class="btn btn-outline-dark py-xl-5 px-5 h-100" href="monitoring">
                <h3 class="mb-5">Monitoring</h3>
                <p>The monitoring page is where users can view the results of various calculations.</p>
            </NavLink>
        </div>
    </div>
</div>
```

2024-01-19 05:46 UTC, ducmvo commented on src/Presentation/Components/Pages/Home.razor
> +<!-- CenteredBoxesWithButtonsAndDescriptions.razor -->
remove this?

2024-01-19 05:46 UTC, ducmvo commented on src/Presentation/Components/Pages/Home.razor
> +
these are not being used, please remove

2024-01-19 05:46 UTC, ducmvo commented on src/Presentation/Components/Pages/Home.razor
> +		<a href="submission" class="home-button">
please replace `a` tag with supported NavLink for navigation
```suggestion
		<NavLink href="dashboard" class="home-button">
```

2024-01-19 05:46 UTC, ducmvo commented on src/Presentation/Components/Pages/Home.razor.css
> +    height: 100vh;
100vh will add extra space to the bottom leads to scollable at initial rendering. Can we fix this?

2024-01-19 05:46 UTC, ducmvo commented on src/Presentation/Components/Pages/Home.razor.css
> +
Can we use bootstrap instead of custom css?

2024-01-22 04:35 UTC, giaou approved these changes

2024-01-23 03:38 UTC, closed without merging