Modified SubmissionForm.razor
DeSimone-Seattle-University-2023-Team2/desimone pull request #23
Opened 2024-01-20 07:45 UTC by giaou

Due to security problem, InputFile component doesnt allow users to retrieve path of selected files. So instead of read the path, Im reading the name of the file.

2024-01-21 06:56 UTC, ducmvo requested changes
Can we have some unit tests?

2024-01-21 06:56 UTC, ducmvo commented on src/Presentation/Components/UI/SubmissionForm.razor
> +    // string filePath1 = "C:/Users/lesli/OneDrive/Desktop/text/file1.txt";
please remove this

2024-01-21 06:56 UTC, ducmvo commented on src/Presentation/Components/UI/SubmissionForm.razor
> +        //await File.AppendAllTextAsync(filePath, "\n\n\n" + e.File.Name);
please remove this

2024-01-21 06:56 UTC, ducmvo commented on src/Presentation/Components/UI/SubmissionForm.razor
> +        System.Diagnostics.Debug.WriteLine(JobModel.InputFile);
we would not want to ship this to prod, please remove

2024-01-21 06:56 UTC, ducmvo commented on src/Presentation/Components/UI/SubmissionForm.razor
> +        System.Diagnostics.Debug.WriteLine(JobModel.InputSupplementDir);
please remove

2024-01-21 06:56 UTC, ducmvo commented on src/Presentation/Components/UI/SubmissionForm.razor
> +        System.Diagnostics.Debug.WriteLine(JobModel.RuntimeConfigFile);
please remove

2024-01-21 06:56 UTC, ducmvo commented on src/Presentation/Components/UI/SubmissionForm.razor
> +        System.Diagnostics.Debug.WriteLine(JobModel.OutputDir);
please remove

2024-01-21 06:56 UTC, ducmvo commented on src/Presentation/Components/UI/SubmissionForm.razor
> +        JobModel.InputFile = e.File.Name;
this is good for now to just save the file name.
We will implement Egnyte file picker to fix this

2024-01-21 07:08 UTC, giaou commented on src/Presentation/Components/UI/SubmissionForm.razor
> +    // string filePath1 = "C:/Users/lesli/OneDrive/Desktop/text/file1.txt";
sure will!! i will remove all the commented out stuff

2024-01-22 03:54 UTC, giaou commented on src/Presentation/Components/UI/SubmissionForm.razor
> +    // string filePath1 = "C:/Users/lesli/OneDrive/Desktop/text/file1.txt";
removed

2024-01-22 03:54 UTC, giaou commented on src/Presentation/Components/UI/SubmissionForm.razor
> +        //await File.AppendAllTextAsync(filePath, "\n\n\n" + e.File.Name);
removed

2024-01-22 03:55 UTC, giaou commented on src/Presentation/Components/UI/SubmissionForm.razor
> +        System.Diagnostics.Debug.WriteLine(JobModel.InputFile);
removed

2024-01-23 03:49 UTC, merged